### ISSUE TITLE
Tests not separated on scenarios in teamcity build

### ISSUE THREAD

**Issue by ailjushkin** [kevinrood/teamcity_formatter#3] opened 2015-12-23 11:31 UTC
@kevinrood Formatter does not display scenario outlines as separate tests in TC Build, something should be changed. Originally, these tests are show up in tab named 'tests' after they appear in the build log.

**Comment by kevinrood** [comment] 2016-01-01 19:01
@PositiveAlex we fan out scenario outline examples and treat each example as a test in TeamCity. You should see `scenario outline name - | example row |` as the test name in TeamCity. Using this approach ensures the test count (passed/failed tests) is the same in TeamCity when compared to running the cucumber tests locally with the default formatter (a primary goal of this gem). The default formatter counts each scenario outline example as a test.

Your further thoughts?

**Comment by kevinrood** [comment] 2016-03-29 21:17
Closing - there were no further comments for some time. The behavior is by design.

**Closed as completed by kevinrood** 2016-03-29 21:17 UTC
